# Generated by Django 6.0.3 on 2026-06-25 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('enrollment', models.CharField()),
                ('roll', models.IntegerField()),
                ('dob', models.DateField()),
                ('title', models.CharField()),
            ],
        ),
    ]
