# Generated by Django 5.2.15 on 2026-07-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_sif_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sif',
            name='enrollment',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sif',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sif',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
